---
- name: Create job to compile a software
  uri:
    url: http://192.168.100.100:8080/createItem?name=Compile-Lighttpd
    method: POST
    HEADER_Content-Type: "application/xml"
    body: "{{ lookup('file','job-config.xml') }}"

- name: Build job
  uri:
    url: http://192.168.100.100:8080/job/Compile-Lighttpd/build?delay=0sec
    method: POST
    status_code: 201
