#!/bin/bash
set -e

if [ ! -d ~/.rvm ]; then
  sudo apt-get update
  sudo apt-get -y upgrade
  gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  \curl -sSL https://get.rvm.io | bash -s stable --ruby=2.2.2
  sudo apt-get -y install nodejs # install js runtime for rails
fi
