#!/bin/bash
echo ""
echo "============== [START] INSTALL LATEST PUPPET =============="
echo ""

sudo apt-get -y install ca-certificates

# It's critical that we use "pc1"; otherwise, we install Puppet v4.x, which
# currently isn't compatible with foreman-installer v1.8
PUPPET_DEB="puppetlabs-release-pc1-trusty.deb"
wget https://apt.puppetlabs.com/$PUPPET_DEB
sudo dpkg -i $PUPPET_DEB
rm $PUPPET_DEB

echo ""
echo "============== [DONE]  INSTALL LATEST PUPPET =============="
echo ""

echo ""
echo "============== [START] GET FOREMAN-INSTALLER =============="
echo ""

echo "deb http://deb.theforeman.org/ trusty 1.8" | sudo tee /etc/apt/sources.list.d/foreman.list
echo "deb http://deb.theforeman.org/ plugins 1.8" | sudo tee -a /etc/apt/sources.list.d/foreman.list
wget -q http://deb.theforeman.org/pubkey.gpg -O- | sudo apt-key add -
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install foreman-installer

echo ""
echo "============== [DONE]  GET FOREMAN-INSTALLER =============="
echo ""
