#!/bin/bash
set -e

if ps aux | grep /usr/share/foreman | grep -v grep 2> /dev/null
then
  echo "================= FOREMAN ALREADY INSTALLED =============="
else
  echo ""
  echo "============== [START] GET FOREMAN-INSTALLER =============="
  echo ""

  echo "deb http://deb.theforeman.org/ trusty 1.8" | sudo tee /etc/apt/sources.list.d/foreman.list
  echo "deb http://deb.theforeman.org/ plugins 1.8" | sudo tee -a /etc/apt/sources.list.d/foreman.list
  wget -q http://deb.theforeman.org/pubkey.gpg -O- | sudo apt-key add -
  sudo apt-get update
  sudo apt-get -y upgrade
  sudo apt-get -y install foreman-installer

  echo ""
  echo "============== [DONE]  GET FOREMAN-INSTALLER =============="
  echo ""

  echo ""
  echo "============== [START] RUN FOREMAN-INSTALLER =============="
  echo ""

  umask 0022 # per documentation on foreman site
  sudo foreman-installer --puppet-server-dynamic-environments true \
    --puppet-server-environments [] \
    --puppet-server-git-repo true \
    --foreman-admin-password "testing-admin"

  echo ""
  echo "============== [DONE]  RUN FOREMAN-INSTALLER =============="
  echo ""
fi
