#!/bin/bash
set -e

echo ""
echo "============== [START] INSTALL PUPPET v3.7.5 =============="
echo ""

sudo apt-get -y install ca-certificates

PUPPET_DEB="puppetlabs-release-trusty.deb"
wget https://apt.puppetlabs.com/$PUPPET_DEB
sudo dpkg -i $PUPPET_DEB
rm $PUPPET_DEB
sudo apt-get update
sudo apt-get -y install puppetmaster=3.7.5-1puppetlabs1 \
  puppet-common=3.7.5-1puppetlabs1 \
  puppetmaster-common=3.7.5-1puppetlabs1

echo ""
echo "============== [DONE]  INSTALL PUPPET v3.7.5 =============="
echo ""
