#!/bin/bash
set -e

if grep "fp-01" /etc/hosts
then
  echo "This machine's /etc/hosts file is already setup"
else
  echo "" | sudo tee --append /etc/hosts 2> /dev/null
  echo "192.168.200.10 fp-01.local fp-01" | sudo tee --append /etc/hosts 2> /dev/null
  sudo rm -rf /etc/puppet/ssl /var/lib/puppet/ssl
fi

sudo cp /vagrant/templates/puppet.conf /etc/puppet/puppet.conf

sudo service puppet stop
sudo service puppet start

sudo puppet resource service puppet ensure=running enable=true
sudo puppet agent --enable
sudo puppet agent --test --waitforcert 60
