# -*- mode: ruby -*-
# vi: set ft=ruby :
hostname = "gmap-poc.local"

Vagrant.configure(2) do |config|
  config.vm.hostname = hostname
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = true
  config.vm.network :forwarded_port, guest: 3000, host: 3000, auto_correct: true

  config.vm.define hostname do |c|
    c.vm.provider :virtualbox do |vb|
      vb.memory = 1024
    end

    c.vm.provision :shell, path: "provisioners/install-rvm-ruby"
    c.vm.provision :shell, path: "provisioners/install-rails-environment"
  end
end
